const json = [
  {
    id: 4,
    title: 'Pull Request 3',
    body: 'This pull request integrates mobile check-in functionality, streamlining the check-in process for passengers using our app, enhancing convenience and efficiency.',
    labels: ['Backend', '4 Days'],

    assignees: [
      {
        login: 'octocat',
        id: 1,
        node_id: 'MDQ6VXNlcjE=',
        avatar_url: 'https://github.com/images/error/octocat_happy.gif',
        gravatar_id: '',
        url: 'https://api.github.com/users/octocat',
        html_url: 'https://github.com/octocat',
        followers_url: 'https://api.github.com/users/octocat/followers',
        following_url: 'https://api.github.com/users/octocat/following{/other_user}',
        gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
        organizations_url: 'https://api.github.com/users/octocat/orgs',
        repos_url: 'https://api.github.com/users/octocat/repos',
        events_url: 'https://api.github.com/users/octocat/events{/privacy}',
        received_events_url: 'https://api.github.com/users/octocat/received_events',
        type: 'User',
        site_admin: false,
      },
      {
        login: 'hubot',
        id: 1,
        node_id: 'MDQ6VXNlcjE=',
        avatar_url: 'https://github.com/images/error/hubot_happy.gif',
        gravatar_id: '',
        url: 'https://api.github.com/users/hubot',
        html_url: 'https://github.com/hubot',
        followers_url: 'https://api.github.com/users/hubot/followers',
        following_url: 'https://api.github.com/users/hubot/following{/other_user}',
        gists_url: 'https://api.github.com/users/hubot/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/hubot/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/hubot/subscriptions',
        organizations_url: 'https://api.github.com/users/hubot/orgs',
        repos_url: 'https://api.github.com/users/hubot/repos',
        events_url: 'https://api.github.com/users/hubot/events{/privacy}',
        received_events_url: 'https://api.github.com/users/hubot/received_events',
        type: 'User',
        site_admin: true,
      },
    ],
    requested_reviewers: [
      {
        login: 'other_user',
        id: 1,
        node_id: 'MDQ6VXNlcjE=',
        avatar_url: 'https://github.com/images/error/other_user_happy.gif',
        gravatar_id: '',
        url: 'https://api.github.com/users/other_user',
        html_url: 'https://github.com/other_user',
        followers_url: 'https://api.github.com/users/other_user/followers',
        following_url: 'https://api.github.com/users/other_user/following{/other_user}',
        gists_url: 'https://api.github.com/users/other_user/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/other_user/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/other_user/subscriptions',
        organizations_url: 'https://api.github.com/users/other_user/orgs',
        repos_url: 'https://api.github.com/users/other_user/repos',
        events_url: 'https://api.github.com/users/other_user/events{/privacy}',
        received_events_url: 'https://api.github.com/users/other_user/received_events',
        type: 'User',
        site_admin: false,
      },
    ],
  },
];

export default json;
